# Generated by Django 6.0.3 on 2026-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
