# Generated by Django 6.0.3 on 2026-04-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='product_qty',
        ),
        migrations.AlterModelTable(
            name='fav',
            table='fav',
        ),
    ]
